M48
; DRILL file KiCad 10.0.5 date 2026-08-25T08:48:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-25T08:48:47-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
%
G90
G05
T1
X37.61Y-91.265
X39.125Y-110.31
X239.61Y-91.265
X241.125Y-110.31
M30
